-- Supply Chain Management
CREATE DATABASE scm;
USE scm;
SHOW TABLES;
RENAME TABLE semiconductors_supply_chain_raw TO scm_table;
SELECT * FROM scm_table
-- ============================================================
-- SECTION 1: ORDER & PROCUREMENT ANALYSIS
-- ============================================================
 
-- Q1 Retrieve the total number of orders placed
SELECT COUNT(Order_ID) AS Total_Orders
FROM scm_table;
 
-- Q2 Calculate the total procurement cost across all suppliers
SELECT SUM(Ordered_Quantity * Unit_Cost) AS Total_Procurement_Cost
FROM scm_table;
 
-- Q3 Identify the supplier with the highest total procurement cost
SELECT Supplier, SUM(Ordered_Quantity * Unit_Cost) AS Total_Cost
FROM scm_table
GROUP BY Supplier
ORDER BY Total_Cost DESC
LIMIT 1;
 
-- Q4 Calculate the average cost per unit for each supplier
SELECT Supplier, AVG(Unit_Cost) AS Average_Unit_Cost
FROM scm_table
GROUP BY Supplier
ORDER BY Average_Unit_Cost DESC;
 
-- Q5 Find the location with the highest total procurement cost
SELECT Location, SUM(Ordered_Quantity * Unit_Cost) AS Total_Cost
FROM scm_table
GROUP BY Location
ORDER BY Total_Cost DESC
LIMIT 1;
 
-- Q6 Retrieve the total quantity ordered from each supplier
SELECT Supplier, SUM(Ordered_Quantity) AS Total_Quantity_Ordered
FROM scm_table
GROUP BY Supplier
ORDER BY Total_Quantity_Ordered DESC;
 
-- Q7 Identify the supplier who supplied the maximum quantity of products
SELECT Supplier, SUM(Ordered_Quantity) AS Total_Quantity_Ordered
FROM scm_table
GROUP BY Supplier
ORDER BY Total_Quantity_Ordered DESC
LIMIT 1;
 
-- Q8 Find the total number of SKUs supplied by each supplier
SELECT Supplier, COUNT(DISTINCT SKU) AS Total_SKUs
FROM scm_table
GROUP BY Supplier
ORDER BY Total_SKUs DESC;
 
-- Q9 Determine the supplier with the widest SKU coverage
SELECT Supplier, COUNT(DISTINCT SKU) AS Total_SKUs
FROM scm_table
GROUP BY Supplier
ORDER BY Total_SKUs DESC
LIMIT 1;
 
 
-- ============================================================
-- SECTION 2: LEAD TIME ANALYSIS
-- ============================================================
 
-- Q10 Calculate the average lead time for each supplier
SELECT Supplier, ROUND(AVG(Avg_Lead_Time), 2) AS Avg_Lead_Time_Days
FROM scm_table
GROUP BY Supplier
ORDER BY Avg_Lead_Time_Days;
 
-- Q11 Identify the supplier with the lowest average lead time
SELECT Supplier, ROUND(AVG(Avg_Lead_Time), 2) AS Avg_Lead_Time_Days
FROM scm_table
GROUP BY Supplier
ORDER BY Avg_Lead_Time_Days ASC
LIMIT 1;
 
-- Q12 Retrieve the month-wise average lead time
SELECT 
    DATE_FORMAT(Order_Date, '%Y-%m') AS Order_Month,
    ROUND(AVG(Avg_Lead_Time), 2) AS Avg_Lead_Time_Days
FROM scm_table
GROUP BY Order_Month
ORDER BY Order_Month;
 
-- Q13 Identify the month with the highest average lead time
SELECT 
    DATE_FORMAT(Order_Date, '%Y-%m') AS Order_Month,
    ROUND(AVG(Avg_Lead_Time), 2) AS Avg_Lead_Time_Days
FROM scm_table
GROUP BY Order_Month
ORDER BY Avg_Lead_Time_Days DESC
LIMIT 1;
 
 
-- ============================================================
-- SECTION 3: QUALITY & INSPECTION ANALYSIS
-- ============================================================
 
-- Q14 Calculate the overall defect rate across all inspections
SELECT ROUND(AVG(Defect_Rate), 2) AS Overall_Defect_Rate
FROM scm_table;
 
-- Q15 Determine the defect rate for each supplier
SELECT Supplier, ROUND(AVG(Defect_Rate), 2) AS Avg_Defect_Rate
FROM scm_table
GROUP BY Supplier
ORDER BY Avg_Defect_Rate DESC;
 
-- Q16 Retrieve the count of inspection results grouped by Pass, Fail, and Pending
SELECT Inspection_Result, COUNT(*) AS Count
FROM scm_table
GROUP BY Inspection_Result
ORDER BY Count DESC;
 
-- Q17 Identify the product category with the highest defect count
SELECT Product_Type, COUNT(*) AS Defect_Count
FROM scm_table
WHERE Inspection_Result = 'Fail'
GROUP BY Product_Type
ORDER BY Defect_Count DESC
LIMIT 1;
 
 
-- ============================================================
-- SECTION 4: REVENUE ANALYSIS
-- ============================================================
 
-- Q18 Calculate total revenue generated from all orders
SELECT ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM scm_table;
 
-- Q19 Retrieve month-wise revenue trend
SELECT 
    DATE_FORMAT(Order_Date, '%Y-%m') AS Order_Month,
    ROUND(SUM(Revenue), 2) AS Monthly_Revenue
FROM scm_table
GROUP BY Order_Month
ORDER BY Order_Month;
 
-- Q20 Identify the month with the highest revenue
SELECT 
    DATE_FORMAT(Order_Date, '%Y-%m') AS Order_Month,
    ROUND(SUM(Revenue), 2) AS Monthly_Revenue
FROM scm_table
GROUP BY Order_Month
ORDER BY Monthly_Revenue DESC
LIMIT 1;
 
-- Q21 Calculate revenue generated by each product type
SELECT Product_Type, ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM scm_table
GROUP BY Product_Type
ORDER BY Total_Revenue DESC;
 
-- Q22 Determine the supplier generating the highest revenue
SELECT Supplier, ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM scm_table
GROUP BY Supplier
ORDER BY Total_Revenue DESC
LIMIT 1;
 
-- Q23 Calculate the average revenue per order
SELECT ROUND(AVG(Revenue), 2) AS Avg_Revenue_Per_Order
FROM scm_table;
 
-- Q24 Retrieve revenue generated by each location and product type
SELECT 
    Location,
    Product_Type,
    ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM scm_table
GROUP BY Location, Product_Type
ORDER BY Location, Total_Revenue DESC;
 
-- Q25 Identify the location with the best cost-to-revenue ratio
SELECT 
    Location,
    ROUND(SUM(Total_Cost), 2) AS Total_Cost,
    ROUND(SUM(Revenue), 2) AS Total_Revenue,
    ROUND(SUM(Total_Cost) / SUM(Revenue), 4) AS Cost_To_Revenue_Ratio
FROM scm_table
GROUP BY Location
ORDER BY Cost_To_Revenue_Ratio ASC
LIMIT 1;
 
 
-- ============================================================
-- SECTION 5: ADVANCED ANALYTICS WITH WINDOW FUNCTIONS
-- ============================================================
 
-- Q26 Calculate the percentage contribution of each supplier to total procurement cost
SELECT 
    Supplier,
    ROUND(SUM(Ordered_Quantity * Unit_Cost), 2) AS Supplier_Cost,
    ROUND(
        SUM(Ordered_Quantity * Unit_Cost) * 100.0 /
        SUM(SUM(Ordered_Quantity * Unit_Cost)) OVER (), 2
    ) AS Cost_Contribution_Pct
FROM scm_table
GROUP BY Supplier
ORDER BY Cost_Contribution_Pct DESC;
 
-- Q27 Rank suppliers based on total procurement cost
SELECT 
    Supplier,
    ROUND(SUM(Ordered_Quantity * Unit_Cost), 2) AS Total_Procurement_Cost,
    RANK() OVER (ORDER BY SUM(Ordered_Quantity * Unit_Cost) DESC) AS Cost_Rank
FROM scm_table
GROUP BY Supplier;
 
-- Q28 Rank suppliers based on average lead time
SELECT 
    Supplier,
    ROUND(AVG(Avg_Lead_Time), 2) AS Avg_Lead_Time_Days,
    RANK() OVER (ORDER BY AVG(Avg_Lead_Time) ASC) AS Lead_Time_Rank
FROM scm_table
GROUP BY Supplier;
 
-- Q29 Identify suppliers with above-average defect rates
SELECT Supplier, ROUND(AVG(Defect_Rate), 2) AS Avg_Defect_Rate
FROM scm_table
GROUP BY Supplier
HAVING Avg_Defect_Rate > (SELECT AVG(Defect_Rate) FROM scm_table)
ORDER BY Avg_Defect_Rate DESC;
 
-- Q30 Analyze cumulative revenue generated over time
SELECT 
    Order_Date,
    ROUND(Revenue, 2) AS Daily_Revenue,
    ROUND(SUM(Revenue) OVER (ORDER BY Order_Date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), 2) AS Cumulative_Revenue
FROM scm_table
ORDER BY Order_Date;
 
-- Q31 Retrieve the top 3 suppliers based on revenue using window functions
SELECT Supplier, Total_Revenue, Revenue_Rank
FROM (
    SELECT 
        Supplier,
        ROUND(SUM(Revenue), 2) AS Total_Revenue,
        DENSE_RANK() OVER (ORDER BY SUM(Revenue) DESC) AS Revenue_Rank
    FROM scm_table
    GROUP BY Supplier
) ranked
WHERE Revenue_Rank <= 3;
 
-- Q32 Determine the top supplier by revenue within each product category
SELECT Product_Type, Supplier, Total_Revenue
FROM (
    SELECT 
        Product_Type,
        Supplier,
        ROUND(SUM(Revenue), 2) AS Total_Revenue,
        RANK() OVER (PARTITION BY Product_Type ORDER BY SUM(Revenue) DESC) AS rnk
    FROM scm_table
    GROUP BY Product_Type, Supplier
) ranked
WHERE rnk = 1
ORDER BY Total_Revenue DESC;
 
 
-- ============================================================
-- SECTION 6: SUPPLIER INTELLIGENCE
-- ============================================================
 
-- Q33 Identify supplier-location combinations with the highest procurement cost
SELECT 
    Supplier,
    Location,
    ROUND(SUM(Ordered_Quantity * Unit_Cost), 2) AS Total_Procurement_Cost
FROM scm_table
GROUP BY Supplier, Location
ORDER BY Total_Procurement_Cost DESC
LIMIT 10;
 
-- Q34 Find suppliers that combine low average cost and low average lead time
-- (Below median on both dimensions — uses average as a proxy threshold)
SELECT 
    Supplier,
    ROUND(AVG(Unit_Cost), 2) AS Avg_Unit_Cost,
    ROUND(AVG(Avg_Lead_Time), 2) AS Avg_Lead_Time_Days
FROM scm_table
GROUP BY Supplier
HAVING 
    Avg_Unit_Cost < (SELECT AVG(Unit_Cost) FROM scm_table)
    AND Avg_Lead_Time_Days < (SELECT AVG(Avg_Lead_Time) FROM scm_table)
ORDER BY Avg_Unit_Cost ASC, Avg_Lead_Time_Days ASC;
 
-- Q35 Identify suppliers that should be flagged due to high cost and high defect rate
SELECT 
    Supplier,
    ROUND(AVG(Unit_Cost), 2) AS Avg_Unit_Cost,
    ROUND(AVG(Defect_Rate), 2) AS Avg_Defect_Rate
FROM scm_table
GROUP BY Supplier
HAVING 
    Avg_Unit_Cost > (SELECT AVG(Unit_Cost) FROM scm_table)
    AND Avg_Defect_Rate > (SELECT AVG(Defect_Rate) FROM scm_table)
ORDER BY Avg_Defect_Rate DESC, Avg_Unit_Cost DESC;